CREATE TABLE LIBROS( _id INTEGER PRIMARY KEY,TITULO TEXT, AUTOR TEXT, PORTADA INTEGER, FAVORITO INTEGER);
INSERT INTO LIBROS VALUES (1,'Música para corazones incendiados','A. M. Homes',1,0);
INSERT INTO LIBROS VALUES (2,'este libro te salvará la vida','A. M. Homes',0,0);
INSERT INTO LIBROS VALUES (3,'Una princesa en Berlín','A. R. G. Solmssen',1,0);
INSERT INTO LIBROS VALUES (4,'El huerfano','Adam Johnson',0,0);
INSERT INTO LIBROS VALUES (5,'Dormir al sol','Adolfo Bioy Casares',1,0);
INSERT INTO LIBROS VALUES (6,'Con lo puesto','Alan Bennett',0,0);
INSERT INTO LIBROS VALUES (7,'La ceremonia del masaje','Alan Bennett',0,0);
INSERT INTO LIBROS VALUES (8,'Solal','Albert Cohen',0,0);
INSERT INTO LIBROS VALUES (9,'Los Indiferentes','Alberto Moravia',1,0);
INSERT INTO LIBROS VALUES (10,'El cabra','Alexandre Jardin',0,0);
INSERT INTO LIBROS VALUES (11,'Amor y amistad','Alison Lurie',0,0);
INSERT INTO LIBROS VALUES (12,'Asuntos Exteriores','Alison Lurie',1,0);
INSERT INTO LIBROS VALUES (13,'La virtud sobre Lorin Jones','Alison Lurie',0,0);
INSERT INTO LIBROS VALUES (14,'Malena es un nombre de tango','Almudena Grandes',1,0);
INSERT INTO LIBROS VALUES (15,'La cuadratura del Circulo','Alvaro Pombo',0,0);
INSERT INTO LIBROS VALUES (16,'Alrededores','Alvaro Pombo',0,0);
INSERT INTO LIBROS VALUES (17,'Estupor y temblores','Amelie Nothomb',0,0);
INSERT INTO LIBROS VALUES (18,'La esposa del Dios del Fuego','Ami Tan',0,0);
INSERT INTO LIBROS VALUES (19,'Soledad de fondo','Anita Brookner',0,0);
INSERT INTO LIBROS VALUES (20,'La Novela de la Lujuria','Anónimo',0,0);
INSERT INTO LIBROS VALUES (21,'El hombre del piano','Anthony Burguess',0,0);
INSERT INTO LIBROS VALUES (22,'Cuentos imprescindibles','Anton Chejov',0,0);
INSERT INTO LIBROS VALUES (23,'Drama en la caceria','Anton Chejov',0,0);
INSERT INTO LIBROS VALUES (24,'La ausencia de Blanca','Antonio Muñoz Molina',0,0);
INSERT INTO LIBROS VALUES (25,'La cabeza perdida de Damasceno M.','Antonio Tabucchi',0,0);
INSERT INTO LIBROS VALUES (26,'Nocturno hindú','Antonio Tabucchi',0,0);
INSERT INTO LIBROS VALUES (27,'El correr de los años','Arthur Miller',0,0);
INSERT INTO LIBROS VALUES (28,'La carta esferica','Arturo Pérez Reverte',0,0);
INSERT INTO LIBROS VALUES (29,'La piel del tambor','Arturo Pérez Reverte',0,0);
INSERT INTO LIBROS VALUES (30,'El pintor de batallas','Arturo Pérez Reverte',0,0);
INSERT INTO LIBROS VALUES (31,'Sharpe y el Aguila del Imperio','Bernard Cornwell',0,0);
INSERT INTO LIBROS VALUES (32,'El lector','Bernhard Schlink',0,0);
INSERT INTO LIBROS VALUES (33,'Infanta','Bodo Kirchhoff',0,0);
INSERT INTO LIBROS VALUES (34,'El arrancacorazones','Boris Vian',0,0);
INSERT INTO LIBROS VALUES (35,'Todos los muertos tienen la misma piel','Boris Vian',0,0);
INSERT INTO LIBROS VALUES (36,'Escupire sobre vuestra tumba','Boris Vian',0,0);
INSERT INTO LIBROS VALUES (37,'Que se mueran los feos','Boris Vian',0,0);
INSERT INTO LIBROS VALUES (38,'Menos que cero','Bret Easton Ellis',0,0);
INSERT INTO LIBROS VALUES (39,'Los Confidentes','Bret Easton Ellis',0,0);
INSERT INTO LIBROS VALUES (40,'American psicho','Bret Easton Ellis',0,0);
INSERT INTO LIBROS VALUES (41,'De cine (memorias de un principe de…)','Budd Schulberg',0,0);
INSERT INTO LIBROS VALUES (42,'Pretérito Imperfecto','C. Castilla del Pino',0,0);
INSERT INTO LIBROS VALUES (43,'La casa del Olivo','C. Castilla del Pino',0,0);
INSERT INTO LIBROS VALUES (44,'Conversaciones con Billy Wilder','Cameron Crowe',0,0);
INSERT INTO LIBROS VALUES (45,'La sombra del viento','Carlos Ruiz Zafón',0,0);
INSERT INTO LIBROS VALUES (46,'Yo fui Johnny Thunders','Carlos Zanon',0,0);
INSERT INTO LIBROS VALUES (47,'Nada','Carmen Laforet',0,0);
INSERT INTO LIBROS VALUES (48,'Nubosidad variable','Carmen Martín Gaite',0,0);
INSERT INTO LIBROS VALUES (49,'Escritos de un viejo indecente','Charles Bukowski',0,0);